### ISSUE TITLE
OpenSSL binary link for Windows 404s

### ISSUE THREAD

**Issue by LPGhatguy** [barrysteyn/node-scrypt#110]
The current README link for installing OpenSSL on Windows gives a 404 right now. It's also a release out of date!

Is there a more general binary download page that would be better to link to?

**Comment by barrysteyn** [comment]
Hi @LPGhatguy 

You are in luck: Version 6 of this module is ready, and I have managed to get rid of all the dependencies to OpenSSL. The only thing that is left for me to do is write the documentation for this version.

Please can you rather install and use this version (it is on branch v6). Also, can you report here your experiences with using it.

Thanks
Barry

**Comment by LPGhatguy** [comment]
Fantastic! As soon as I get home from the office I'll take a look since I was having some issues getting v5.x to work on Windows.

**Comment by barrysteyn** [comment]
@LPGhatguy Please can you tell me via this forum if it works for you. This module does resquire a C++ version 11 compiler (actually, any Node add-on requires this nowadays), so if you have windows, you will need msvc++2013 (any version below this will not support C++ 11)

**Comment by barrysteyn** [comment]
Hi. Did it work?

**Comment by LPGhatguy** [comment]
I was able to compile the module successfully, but I didn't test the resulting installation. I hit a snag with the VS 2013 compiler dying without reporting any errors but was able to get VS 2015 working just fine.

**Comment by LPGhatguy** [comment]
I hit an issue trying to install the module's v6 branch via `npm`, however. `node-gyp` is correctly installed and my compiler is on my path:

```
C:\projects\web\meta-archive>npm install https://github.com/barrysteyn/node-scrypt#v6
npm WARN install Couldn't install optional dependency: Unsupported

> scrypt@5.4.1 preinstall C:\projects\web\meta-archive\node_modules\.staging\scrypt-2bf2f79f83853b67ab7de0cefb196c7b
> node node-scrypt-preinstall.js


> scrypt@5.4.1 install C:\projects\web\meta-archive\node_modules\scrypt
> node-gyp rebuild


C:\projects\web\meta-archive\node_modules\scrypt>if not defined npm_config_node_gyp (node "C:\Users\Lucien\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: spawn python2 ENOENT
gyp ERR! stack     at exports._errnoException (util.js:856:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:179:32)
gyp ERR! stack     at onErrorNT (internal/child_process.js:345:16)
gyp ERR! stack     at nextTickCallbackWith2Args (node.js:455:9)
gyp ERR! stack     at process._tickCallback (node.js:369:17)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\dev\\nodejs\\node.exe" "C:\\Users\\Lucien\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\projects\web\meta-archive\node_modules\scrypt
gyp ERR! node -v v5.2.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\dev\\nodejs\\node.exe" "C:\\Users\\Lucien\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "https://github.com/barrysteyn/node-scrypt#v6"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.7
npm ERR! code ELIFECYCLE

npm ERR! scrypt@5.4.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@5.4.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the scrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls scrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\projects\web\meta-archive\npm-debug.log

C:\projects\web\meta-archive>node-gyp

  Usage: node-gyp <command> [options]

  where <command> is one of:
    - build - Invokes `msbuild` and builds the module
    - clean - Removes any generated build files and the "out" dir
    - configure - Generates MSVC project files for the current module
    - rebuild - Runs "clean", "configure" and "build" all at once
    - install - Install node development files for the specified node version.
    - list - Prints a listing of the currently installed node development files
    - remove - Removes the node development files for the specified version

node-gyp@3.2.1  C:\Users\Lucien\AppData\Roaming\npm\node_modules\node-gyp
node@5.2.0

C:\projects\web\meta-archive>which node-gyp
C:\Users\Lucien\AppData\Roaming\npm\node-gyp

C:\projects\web\meta-archive>msbuild
Microsoft (R) Build Engine version 14.0.23107.0
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.
```

**Comment by LPGhatguy** [comment]
I hit an issue trying to install the module via npm, however:

```
C:\projects\web\meta-archive>npm install https://github.com/barrysteyn/node-scrypt.git#v6
npm WARN install Couldn't install optional dependency: Unsupported

> scrypt@5.4.1 preinstall C:\projects\web\meta-archive\node_modules\.staging\scrypt-2bf2f79f83853b67ab7de0cefb196c7b
> node node-scrypt-preinstall.js


> scrypt@5.4.1 install C:\projects\web\meta-archive\node_modules\scrypt
> node-gyp rebuild


C:\projects\web\meta-archive\node_modules\scrypt>if not defined npm_config_node_gyp (node "C:\Users\Lucien\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: spawn python2 ENOENT
gyp ERR! stack     at exports._errnoException (util.js:856:11)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:179:32)
gyp ERR! stack     at onErrorNT (internal/child_process.js:345:16)
gyp ERR! stack     at nextTickCallbackWith2Args (node.js:455:9)
gyp ERR! stack     at process._tickCallback (node.js:369:17)
gyp ERR! System Windows_NT 10.0.10240
gyp ERR! command "C:\\dev\\nodejs\\node.exe" "C:\\Users\\Lucien\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\projects\web\meta-archive\node_modules\scrypt
gyp ERR! node -v v5.2.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
npm ERR! Windows_NT 10.0.10240
npm ERR! argv "C:\\dev\\nodejs\\node.exe" "C:\\Users\\Lucien\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "https://github.com/barrysteyn/node-scrypt.git#v6"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.7
npm ERR! code ELIFECYCLE

npm ERR! scrypt@5.4.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@5.4.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the scrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls scrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\projects\web\meta-archive\npm-debug.log
```

My environment appears to be correct, however:
```
C:\projects\web\meta-archive>python -V
Python 2.7.9

C:\projects\web\meta-archive>msbuild -V
Microsoft (R) Build Engine version 14.0.23107.0
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1016: Specify the verbosity level.
Switch: -V

For switch syntax, type "MSBuild /help"

C:\projects\web\meta-archive>node-gyp -v
v3.2.1

C:\projects\web\meta-archive>node -v
v5.2.0
```

**Comment by LPGhatguy** [comment]
Are there any updates on fixing this compilation issue? It seems like there are just some files missing from the repository potentially, or maybe I'm missing a dependency.

**Comment by barrysteyn** [comment]
Version 6 has been released, and it does not depend on an external openssl library. So this should be a non-issue now.
