### ISSUE TITLE
OS X. Failed to install 

### ISSUE THREAD

**Issue by velocityzen** [barrysteyn/node-scrypt#113]
```
tmp ❯ npm i scrypt --save

> scrypt@5.4.1 install /Users/velocityzen/Projects/tmp/node_modules/scrypt
> node-gyp rebuild

  COPY ../scrypt/scrypt-1.1.6/config.h
  SOLINK_MODULE(target) Release/copied_files.node
  CC(target) Release/obj.target/scrypt_wrapper/src/util/salt.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/keyderivation.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/pickparams.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/hash.o
  LIBTOOL-STATIC Release/scrypt_wrapper.a
Usage: /usr/local/bin/libtool [OPTION]... [MODE-ARG]...
Try 'libtool --help' for more information.
libtool:   error: unrecognised option: '-static'
make: *** [Release/scrypt_wrapper.a] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/velocityzen/Projects/tmp/node_modules/scrypt
gyp ERR! node -v v5.5.0
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm WARN ENOENT ENOENT: no such file or directory, open '/Users/velocityzen/Projects/tmp/package.json'
npm WARN EPACKAGEJSON tmp No description
npm WARN EPACKAGEJSON tmp No repository field.
npm WARN EPACKAGEJSON tmp No README data
npm WARN EPACKAGEJSON tmp No license field.
npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "scrypt" "--save"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! scrypt@5.4.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt@5.4.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the scrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls scrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/velocityzen/Projects/tmp/npm-debug.log
```

**Comment by velocityzen** [comment]
```
tmp ❯ libtool --version
libtool (GNU libtool) 2.4.6
```

**Comment by barrysteyn** [comment]
Please try version 6. I think it will fix your problem.

tmp ❯ libtool --version
libtool (GNU libtool) 2.4.6

—
Reply to this email directly or view it on GitHub
<https://github.com/barrysteyn/node-scrypt/issues/113#issuecomment-179517352>
.

**Comment by velocityzen** [comment]
@barrysteyn same `libtool:   error: unrecognised option: '-static'`

**Comment by barrysteyn** [comment]
Okay, I will look into this over the weekend. I'll do this on my Mac. Try
to publish on Monday

**Comment by velocityzen** [comment]
@barrysteyn thanks!

**Comment by velocityzen** [comment]
I found a problem. I have another version of libtool installed in /usr/local/bin/libtool. 
You should use OSX stock libtool from /usr/bin/libtool

**Comment by barrysteyn** [comment]
Hi Alexey

I don't explicitly use any libtool, that is the job of node-gyp. I think
that node-gyp just looks for the libtool in the standard place. Look for
node-gyp on npm, there is documentation there, perhaps you can change the
libtool search path.


Barry Steyn
Blog <http://doctrina.org> LinkedIn <http://ca.linkedin.com/in/barrysteyn>
GitHub <https://github.com/barrysteyn>

**Comment by velocityzen** [comment]
Ok, then it's a node-gyp problem :+1:

**Comment by lbrth** [comment]
Sorry to reopen this, but could you explain how you fixed this problem exactly ? thanks !

**Comment by makc** [comment]
@lbrth this worked for me:
```
mv /usr/local/bin/libtool /usr/local/bin/libtool.bak
npm install scrypt
mv /usr/local/bin/libtool.bak /usr/local/bin/libtool
```

CC #155

**Comment by nghiadt16** [comment]
@makc thank you so so much! I spent a lot of time to deal with it :(

**Comment by yiakwy** [comment]
@makc This is a much cleaner solution with minimum side effects
