### ISSUE TITLE
Scrypt will not install on my Raspberry Pi Zero

### ISSUE THREAD

**Issue by LordWingZero** [barrysteyn/node-scrypt#122]
Install scrypt-for-humans installs node scrypt 5.4.0 which fails to install with the following errors.

## Pi Zero
Linux raspbain_pi_zero 4.1.17+ #838 Tue Feb 9 12:57:10 GMT 2016 armv6l GNU/Linux

## npm output
```
npm install scrypt-for-humans

> scrypt@5.4.1 install /home/pi/Apps/failreactor/node_modules/scrypt
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
sub/conftst1.h { dev: 45831,
  mode: 33188,
  nlink: 1,
  uid: 1000,
  gid: 1000,
  rdev: 0,
  blksize: 4096,
  ino: 401962,
  size: 0,
  blocks: 0,
  atime: Fri Mar 04 2016 16:02:17 GMT+0000 (UTC),
  mtime: Fri Mar 04 2016 16:02:17 GMT+0000 (UTC),
  ctime: Fri Mar 04 2016 16:02:17 GMT+0000 (UTC),
  birthtime: Fri Mar 04 2016 16:02:17 GMT+0000 (UTC) }
sub/conftst2.h { dev: 45831,
  mode: 33188,
  nlink: 1,
  uid: 1000,
  gid: 1000,
  rdev: 0,
  blksize: 4096,
  ino: 401963,
  size: 0,
  blocks: 0,
  atime: Fri Mar 04 2016 16:02:18 GMT+0000 (UTC),
  mtime: Fri Mar 04 2016 16:02:18 GMT+0000 (UTC),
  ctime: Fri Mar 04 2016 16:02:18 GMT+0000 (UTC),
  birthtime: Fri Mar 04 2016 16:02:18 GMT+0000 (UTC) }
sub/conftst3.h { dev: 45831,
  mode: 33188,
  nlink: 1,
  uid: 1000,
  gid: 1000,
  rdev: 0,
  blksize: 4096,
  ino: 401964,
  size: 0,
  blocks: 0,
  atime: Fri Mar 04 2016 16:02:20 GMT+0000 (UTC),
  mtime: Fri Mar 04 2016 16:02:20 GMT+0000 (UTC),
  ctime: Fri Mar 04 2016 16:02:20 GMT+0000 (UTC),
  birthtime: Fri Mar 04 2016 16:02:20 GMT+0000 (UTC) }
sub/conftst4.h { dev: 45831,
  mode: 33188,
  nlink: 1,
  uid: 1000,
  gid: 1000,
  rdev: 0,
  blksize: 4096,
  ino: 401965,
  size: 0,
  blocks: 0,
  atime: Fri Mar 04 2016 16:02:22 GMT+0000 (UTC),
  mtime: Fri Mar 04 2016 16:02:22 GMT+0000 (UTC),
  ctime: Fri Mar 04 2016 16:02:22 GMT+0000 (UTC),
  birthtime: Fri Mar 04 2016 16:02:22 GMT+0000 (UTC) }
sub/conftst5.h { dev: 45831,
  mode: 33188,
  nlink: 1,
  uid: 1000,
  gid: 1000,
  rdev: 0,
  blksize: 4096,
  ino: 401966,
  size: 0,
  blocks: 0,
  atime: Fri Mar 04 2016 16:02:23 GMT+0000 (UTC),
  mtime: Fri Mar 04 2016 16:02:23 GMT+0000 (UTC),
  ctime: Fri Mar 04 2016 16:02:23 GMT+0000 (UTC),
  birthtime: Fri Mar 04 2016 16:02:23 GMT+0000 (UTC) }
sub/conftst6.h { dev: 45831,
  mode: 33188,
  nlink: 1,
  uid: 1000,
  gid: 1000,
  rdev: 0,
  blksize: 4096,
  ino: 401967,
  size: 0,
  blocks: 0,
  atime: Fri Mar 04 2016 16:02:25 GMT+0000 (UTC),
  mtime: Fri Mar 04 2016 16:02:25 GMT+0000 (UTC),
  ctime: Fri Mar 04 2016 16:02:25 GMT+0000 (UTC),
  birthtime: Fri Mar 04 2016 16:02:25 GMT+0000 (UTC) }
gyp: Call to 'scrypt/configuration/posixconfig' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/pi/.nvm/versions/node/v5.7.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 4.1.17+
gyp ERR! command "/home/pi/.nvm/versions/node/v5.7.0/bin/node" "/home/pi/.nvm/versions/node/v5.7.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/Apps/failreactor/node_modules/scrypt
gyp ERR! node -v v5.7.0
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok
Failreactor@1.0.0 /home/pi/Apps/failreactor
├─┬ bookshelf@0.9.2
│ └── bluebird@2.10.2
├─┬ express-promise-router@1.0.0
│ └── bluebird@2.10.2
├─┬ express-validator@2.19.1
│ └── bluebird@2.10.2
├─┬ knex@0.9.0
│ └── bluebird@2.10.2
└─┬ sqlite3@3.1.1
  └─┬ node-pre-gyp@0.6.14
    └─┬ request@2.64.0
      └─┬ har-validator@1.8.0
        └── bluebird@2.10.2

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.8
npm ERR! Linux 4.1.17+
npm ERR! argv "/home/pi/.nvm/versions/node/v5.7.0/bin/node" "/home/pi/.nvm/versions/node/v5.7.0/bin/npm" "install" "scrypt-for-humans"
npm ERR! node v5.7.0
npm ERR! npm  v3.7.5
npm ERR! code ELIFECYCLE

npm ERR! scrypt@5.4.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@5.4.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the scrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs scrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls scrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/Apps/failreactor/npm-debug.log

```

## [npm-debug.log](https://drive.google.com/file/d/0B0JBNCwYjUsnckU3b3pTX2h2U2M/view?usp=sharing)

**Comment by barrysteyn** [comment]
You need to use the latest version of Scrypt (version 6.01). Reopen this issue if that does not solve the problem.
