### ISSUE TITLE
Install requires python?

### ISSUE THREAD

**Issue by RHavar** [barrysteyn/node-scrypt#124]
I'm getting this:

```
$ npm install scrypt
npm WARN lifecycle scrypt@6.0.1~preinstall: cannot run in wd %s %s (wd=%s) scrypt@6.0.1 node node-scrypt-preinstall.js /tmp/catsoup/node_modules/.staging/scrypt-11bb8a17

> buffertools@2.1.3 install /tmp/catsoup/node_modules/buffertools
> node-gyp rebuild

gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:401:14)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:330:11
gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:63:16)
gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:72:29)
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:81:16
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/index.js:44:5
gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/node_modules/isexe/access.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:82:15)
gyp ERR! System Linux 4.2.0-18-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/hookedin/node_modules/buffertools
gyp ERR! node -v v5.8.0
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok 
npm WARN install:buffertools@2.1.3 buffertools@2.1.3 install: `node-gyp rebuild`
npm WARN install:buffertools@2.1.3 Exit status 1
```

Is python a hard dependency of using scrypt? Ideally I'd keep my production machines lean and mean without it =)

**Comment by barrysteyn** [comment]
node-gyp is a tool that is used to build the program. It requires python. So install python and things should work. Look at the instructions for node-gyp if you need help.
