### ISSUE TITLE
No such file or directory (nan.h)

### ISSUE THREAD

**Issue by AttilaSATAN** [barrysteyn/node-scrypt#134]
windows 10
with node-gyp and windows-build-tools

compiler try to include a header file called 'nan.h' but can't find it. 

```.\src\node-boilerplate\scrypt_kdf_async.cc(1): fatal error C1083: Cannot open include file: 'nan.h': No such file or directory (compiling source file ..\src\n
de-boilerplate\scrypt_kdf_async.cc) [D:\Dev\İpsizcambaz\ic-json-api-framework\node_modules\scrypt\build\scrypt.vcxproj]```

I get this error on compilation of...

* `scrypt_params_sync.cc)`
* `scrypt_params_async.cc`
* `scrypt_kdf_async.cc`
* `scrypt_kdf_sync.cc`
* `scrypt_kdf-verify_sync.cc`
* `scrypt_kdf-verify_async.cc`
* `scrypt_hash_sync.cc`
* `scrypt_hash_async.cc`
* `scrypt_node.cc`
* `scrypt_common.cc`

**Comment by barrysteyn** [comment]
I will look into this on Sat.

**Comment by Kresshy** [comment]
Sadly I have a similar issue which I think can be related to this, running on OS X, Node 5.6 and npm 3

```
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  COPY ../scrypt/scrypt-1.1.6/config.h
  SOLINK_MODULE(target) Release/copied_files.node
  CC(target) Release/obj.target/scrypt_wrapper/src/util/salt.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/keyderivation.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/pickparams.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/hash.o
  LIBTOOL-STATIC Release/scrypt_wrapper.a
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/crypto/sha256.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/crypto/crypto_scrypt-sse.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/scryptenc/scryptenc_cpuperf.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/util/memlimit.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/scryptenc/scryptenc.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/crypto/crypto_aesctr.o
  LIBTOOL-STATIC Release/scrypt_lib.a
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_common.o
../src/node-boilerplate/scrypt_common.cc:76:3: error: use of undeclared identifier
      'NanEscapableScope'
                NanEscapableScope();
                ^
../src/node-boilerplate/scrypt_common.cc:77:30: error: use of undeclared identifier
      'NanError'
                v8::Local<v8::Value> err = NanError(ScryptErrorDescr(error), error);
                                           ^
../src/node-boilerplate/scrypt_common.cc:79:12: error: use of undeclared identifier
      'NanNew'
                obj->Set(NanNew<v8::String>("name"), NanNew<v8::String>("ScryptError"));
                         ^
../src/node-boilerplate/scrypt_common.cc:79:29: error: expected '(' for function-style
      cast or type construction
                obj->Set(NanNew<v8::String>("name"), NanNew<v8::String>("ScryptError"));
                                ~~~~~~~~~~^
../src/node-boilerplate/scrypt_common.cc:79:40: error: use of undeclared identifier
      'NanNew'
                obj->Set(NanNew<v8::String>("name"), NanNew<v8::String>("ScryptError"));
                                                     ^
../src/node-boilerplate/scrypt_common.cc:79:57: error: expected '(' for function-style
      cast or type construction
                obj->Set(NanNew<v8::String>("name"), NanNew<v8::String>("ScryptError"));
                                                            ~~~~~~~~~~^
../src/node-boilerplate/scrypt_common.cc:80:10: error: use of undeclared identifier
      'NanEscapeScope'
                return NanEscapeScope(err);
                       ^
7 errors generated.
make: *** [Release/obj.target/scrypt/src/node-boilerplate/scrypt_common.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:100:13)
gyp ERR! stack     at ChildProcess.emit (events.js:185:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/bin/node-gyp" "configure" "build"
gyp ERR! cwd /Users/svaradi/workplace/authentication-service/node_modules/scrypt
gyp ERR! node -v v5.6.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
```

**Comment by Danultimate** [comment]
@Kresshy did you solve this? Im having the same issue.
