### ISSUE TITLE
Issue with installing in Docker

### ISSUE THREAD

**Issue by justin-nodeboy** [barrysteyn/node-scrypt#148]
Hey Barry

I am having real issues getting this working with Docker :/

Here is my current Dockerfile

```bash
FROM node:7.5.0-alpine
ADD . /app
WORKDIR /app

RUN npm install mocha -g
RUN npm install nodemon -g

RUN apk add --update python krb5 krb5-libs gcc make g++ krb5-dev

# Install app dependencies
ADD package.json /src/package.json
RUN npm install
RUN npm test

EXPOSE 3443

CMD ["node", "app.js"]

ENV BRAND="Epic POS"
ENV PORT=3443
ENV NODE_ENV="development"
ENV NODE_TLS_REJECT_UNAUTHORIZED=0
ENV MONGODB_URI="mongodb://172.19.0.2:27017/epic-pos"
```

Here is my docker-compose.yml

```version: "3"

services:
    api:
        image: epicsoftware/epic-pos
        command: npm start
        ports: 
            - "3443:3443"
        networks: 
            - epic-pos-bridge
        volumes: 
            - ./pos-api:/app
        links: 
            - db
    db:
        image: mongo
        container_name: db
        networks: 
            - epic-pos-bridge    
        volumes:
            - "db-data:/var/lib/mongo/data"

volumes:
  db-data:

networks:
    epic-pos-bridge:  
```

This is the error that gets raised when I run docker-compose up

```bash
api_1  | Error: Error loading shared library /app/node_modules/scrypt/build/Release/scrypt.node: Exec format error
api_1  |     at Object.Module._extensions..node (module.js:598:18)
api_1  |     at Module.load (module.js:488:32)
api_1  |     at tryModuleLoad (module.js:447:12)
api_1  |     at Function.Module._load (module.js:439:3)
api_1  |     at Module.require (module.js:498:17)
api_1  |     at require (internal/module.js:20:19)
api_1  |     at Object.<anonymous> (/app/node_modules/scrypt/index.js:3:20)
api_1  |     at Module._compile (module.js:571:32)
api_1  |     at Object.Module._extensions..js (module.js:580:10)
api_1  |     at Module.load (module.js:488:32)
```

Any ideas on what might be causing that? I've spent the best part of 4 hours balls deep in Google and not getting anywhere really (apart from getting it installed by adding `RUN apk add --update python krb5 krb5-libs gcc make g++ krb5-dev` which caused me the first load of issues)

**Comment by barrysteyn** [comment]
See #150

**Comment by JaniPete** [comment]
Could it be that your container's node_modules folder will be hidden by host's node_modules folder after you have mounted your development folder? So you actually get the version of script that were built on top of different architecture?

How this works on my MacOS Docker is that I don't have this line in the Docker file: 
RUN apk add --update python krb5 krb5-libs gcc make g++ krb5-dev

And then in addition to api - volumes part docker-compose.yml I need to mount node_modules directory from my container in order to prevent hiding. So I add one additional volume like this:
- /app/node_modules

**Comment by SamuelMarks** [comment]
Thanks @JaniPM; the really helped me 😀

**Comment by SamuelMarks** [comment]
Thanks @JaniPM; that really helped me 😀
