### ISSUE TITLE
Installing etheratom errors

### ISSUE THREAD

**Issue by Aconitin** [barrysteyn/node-scrypt#152]
Hey, When I try to install etheratom, it fails with this error:

`> scrypt@6.0.3 preinstall C:\Users\Sven\AppData\Local\Temp\apm-install-dir-117424-6572-1ax57bw.037rwfjemi\node_modules\.staging\scrypt-03eb5f47
> node node-scrypt-preinstall.js

> scrypt@6.0.3 install C:\Users\Sven\AppData\Local\Temp\apm-install-dir-117424-6572-1ax57bw.037rwfjemi\node_modules\etheratom\node_modules\scrypt
> node-gyp rebuild

C:\Users\Sven\AppData\Local\Temp\apm-install-dir-117424-6572-1ax57bw.037rwfjemi\node_modules\etheratom\node_modules\scrypt>if not defined npm_config_node_gyp (node "C:\Users\Sven\AppData\Local\atom\app-1.17.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Sven\AppData\Local\atom\app-1.17.0\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
Warning: Missing input files:
C:\Users\Sven\AppData\Local\Temp\apm-install-dir-117424-6572-1ax57bw.037rwfjemi\node_modules\etheratom\node_modules\scrypt\build\..\scrypt\win\include\config.h
Die Projekte in dieser Projektmappe werden nacheinander erstellt. Um eine parallele Erstellung zu erm�glichen, m�ssen Sie den Schalter "/m" hinzuf�gen.
MSBUILD : error MSB3428: Die Visual C++-Komponente "VCBuild.exe" konnte nicht geladen werden. Um dieses Problem zu beheben, installieren Sie entweder 1) .NET Framework 2.0 SDK oder 2) Microsoft Visual Studio 2005 oder 3) f�gen Sie den Speicherort der Komponente zum Systempfad hinzu, falls er vom Standardspeicherort abweicht.  [C:\Users\Sven\AppData\Local\Temp\apm-install-dir-117424-6572-1ax57bw.037rwfjemi\node_modules\etheratom\node_modules\scrypt\build\binding.sln]
MSBUILD : error MSB3428: Die Visual C++-Komponente "VCBuild.exe" konnte nicht geladen werden. Um dieses Problem zu beheben, installieren Sie entweder 1) .NET Framework 2.0 SDK oder 2) Microsoft Visual Studio 2005 oder 3) f�gen Sie den Speicherort der Komponente zum Systempfad hinzu, falls er vom Standardspeicherort abweicht.  [C:\Users\Sven\AppData\Local\Temp\apm-install-dir-117424-6572-1ax57bw.037rwfjemi\node_modules\etheratom\node_modules\scrypt\build\binding.sln]
C:\Users\Sven\AppData\Local\Temp\apm-install-dir-117424-6572-1ax57bw.037rwfjemi
`-- (empty)

(node:3064) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:3064) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:3064) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:3064) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:3064) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:3064) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:3064) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:3064) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:3064) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:3064) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:3064) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:3064) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:3064) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:3064) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:3064) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
(node:3064) Warning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit
gyp ERR! build error 
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Sven\AppData\Local\atom\app-1.17.0\resources\app\apm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.10586
gyp ERR! command "C:\\Users\\Sven\\AppData\\Local\\atom\\app-1.17.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Sven\\AppData\\Local\\atom\\app-1.17.0\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Sven\AppData\Local\Temp\apm-install-dir-117424-6572-1ax57bw.037rwfjemi\node_modules\etheratom\node_modules\scrypt
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\Sven\AppData\Local\Temp\apm-install-dir-117424-6572-1ax57bw.037rwfjemi\package.json'
npm WARN apm-install-dir-117424-6572-1ax57bw.037rwfjemi No description
npm WARN apm-install-dir-117424-6572-1ax57bw.037rwfjemi No repository field.
npm WARN apm-install-dir-117424-6572-1ax57bw.037rwfjemi No README data
npm WARN apm-install-dir-117424-6572-1ax57bw.037rwfjemi No license field.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Users\\Sven\\AppData\\Local\\atom\\app-1.17.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\Sven\\AppData\\Local\\atom\\app-1.17.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\Sven\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\Sven\\.atom\\.apmrc" "install" "C:\\Users\\Sven\\AppData\\Local\\Temp\\d-117424-6572-1r9ke2k.v6c8k0rudi\\package.tgz" "--runtime=electron" "--target=1.3.15" "--arch=ia32" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE

npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt@6.0.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the scrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs scrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls scrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Sven\AppData\Local\Temp\apm-install-dir-117424-6572-1ax57bw.037rwfjemi\npm-debug.log
npm ERR! code 1`

I am running Win10 & have the latest node.js. Now, the file it tells me to provide (in the end) doesn't exist, but I found another log in the Atom_crashes ffolder with a current timestamp that might help ...
[operation_log.txt](https://github.com/barrysteyn/node-scrypt/files/1026320/operation_log.txt)

**Comment by fanatid** [comment]
try install https://github.com/felixrieseberg/windows-build-tools
and reinstall `node-scrypt` after this

**Comment by Aconitin** [comment]
Worked, thanks!

**Comment by davux** [comment]
@fanatid's Your solution does work, thanks!

What do you think the root problem is, @barrysteyn? Many people seem to be facing the same issue when installing some modules on Windows 7, e.g. `solidity-repl`, `ethereumjs-testrpc`, `truffle`...

**Comment by fanatid** [comment]
`node-scrypt` should use https://github.com/mafintosh/prebuild
this will solve many problems

**Comment by ne0ark** [comment]
I am getting warning on ubuntu:

npm WARN lifecycle scrypt@6.0.3~preinstall: cannot run in wd %s %s (wd=%s) scrypt@6.0.3 node node-scrypt-preinstall.js /usr/lib/node_modules/.staging/scrypt-337cb8ab
