### ISSUE TITLE
node-gyp rebuild fails when Python is via miniconda

### ISSUE THREAD

**Issue by voltagex** [barrysteyn/node-scrypt#154]
```
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "C:\Users\Adam\Miniconda3\python.EXE", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:454:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:480:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:114:15)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\git\c20294d63012c4947d5cc052c9414c8f\node_modules\scrypt
gyp ERR! node -v v7.9.0
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok 
npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt@6.0.3 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the scrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs scrypt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls scrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Adam\AppData\Roaming\npm-cache\_logs\2017-06-02T13_44_02_741Z-debug.log
```

The Python interpreter is definitely there.

[2017-06-02T13_44_02_741Z-debug.log.txt](https://github.com/barrysteyn/node-scrypt/files/1047828/2017-06-02T13_44_02_741Z-debug.log.txt)

**Comment by fanatid** [comment]
> The Python interpreter is definitely there.

```
gyp ERR! stack Error: Can't find Python executable "C:\Users\Adam\Miniconda3\python.EXE", you can set the PYTHON env variable.
```

**Comment by voltagex** [comment]
```
C:\git\c20294d63012c4947d5cc052c9414c8f>C:\Users\Adam\Miniconda3\python.EXE
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 11:57:41) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

The issue is probably that node-gyp doesn't support Python 3.
