### ISSUE TITLE
Invalid ELF header docker

### ISSUE THREAD

**Issue by amosyuen** [barrysteyn/node-scrypt#160]
I tried installing `node-scrypt` in a ubuntu docker container running on Windows. Install worked fine, but requiring it gives me this error:

```
api_1  |   module.js:653
api_1  |   return process.dlopen(module, path._makeLong(filename));
api_1  |                  ^
api_1  |
api_1  | Error: /code/api/src/node_modules/node-scrypt/build/default/scrypt.node: invalid ELF header
api_1  |     at Object.Module._extensions..node (module.js:653:18)
api_1  |     at Module.load (module.js:545:32)
api_1  |     at tryModuleLoad (module.js:508:12)
api_1  |     at Function.Module._load (module.js:500:3)
api_1  |     at Module.require (module.js:568:17)
api_1  |     at require (internal/module.js:11:18)
api_1  |     at Object.<anonymous> (/code/api/src/node_modules/node-scrypt/scrypt.js:1:14)
api_1  |     at Module._compile (module.js:624:30)
api_1  |     at Module._extensions..js (module.js:635:10)
api_1  |     at Object.require.extensions.(anonymous function) [as .js] (/code/api/src/node_modules/babel-register/lib/node.js:152:7)
api_1  |     at Module.load (module.js:545:32)
api_1  |     at tryModuleLoad (module.js:508:12)
api_1  |     at Function.Module._load (module.js:500:3)
api_1  |     at Module.require (module.js:568:17)
api_1  |     at require (internal/module.js:11:18)
api_1  |     at Object.<anonymous> (/code/api/src/app/v1/auth/local/passwords/versions/v0.js:2:1)
```

**Comment by greggmojica** [comment]
Same issue!

**Comment by murich** [comment]
Same issue except the fix didn't work for me :(

**Comment by quantumproducer** [comment]
Same, I tried copying over the build output and everything inside of release to the node_modules/node-scrypt directory, no success.

This works fine on my local machine, fails on an Ubuntu server.

**Comment by stasbar** [comment]
Same problem here. Any fixes ?

**Comment by mseijas** [comment]
I'm having the same issue. Have any of you been able to resolve this?

**Comment by stasbar** [comment]
I'm not sure what happened, but for me the solution was to reboot

**Comment by haohaowasky** [comment]
same issue!

**Comment by pb-expa** [comment]
Actually got it working guys.

For whoever comes across this in the future, the issue DOES comes down to how you handle the node_module folder generation. However, It may not be enough for you to simply .dockerignore it, for me I had to set up docker to explicitly regenerate the node_module folder. This came down to doing 3 things:

1. Dockerfile (make sure you are copying your package.json):
FROM node:8

# Create application dir
WORKDIR /usr/src/code

# Copy the package.json this is important
COPY package.json /usr/src/code

# Install
RUN yarn install
......


2. .dockerignore (make sure you are ignoring your node_modules)
dump.rdb
*.log
**/node_modules
.....

3. Dockerfile (set up a node_modules folder in the volumes)
version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/code
      - /usr/src/code/node_modules/
      - logvolume01:/var/log
    links:
      - redis
    depends_on:
      - db
      - redis
.......


When i did all three of these, the project finally compiled correctly. Hope this helps!
