### ISSUE TITLE
Can not find module scrypt from index.js

### ISSUE THREAD

**Issue by criticalbh** [barrysteyn/node-scrypt#162]
It looks like `var scryptNative = require("./build/Release/scrypt")` can not be found.
If I replace this with `var scryptNative = require("./build/Release/scrypt.node")` it works.

Here is the error message:

```
    Cannot find module './build/Release/scrypt' from 'index.js'
      
      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:179:17)
      at Object.<anonymous> (node_modules/mymodule/node_modules/scrypt/index.js:3:20)

```

**Comment by fanatid** [comment]
PR #144 
https://github.com/TooTallNate/node-bindings/blob/58141c6ce00b2f7690d7115e6635fdd5739b7fd0/bindings.js#L65

**Comment by amazingandyyy** [comment]
can we fix this asap?

**Comment by ryanio** [comment]
+1

**Comment by admazzola** [comment]
For right now, I am cloning a local copy of the scrypt repo and changing that line  from  the   require("./build/Release/scrypt") to  require("./build/Release/scrypt.node")    and then adding 'node-loader' to webpack config and it works fine.  However yes we will need an official fix for this :)   Also some note that youll need node-loader

**Comment by Levino** [comment]
I created a [patch file](https://gist.github.com/Levino/2bf0c9df879843fcadc5b38acfeba39a) for `scrypt` to be used with [patch-package](https://www.npmjs.com/package/patch-package)

**Comment by or2008** [comment]
any updates on this?

**Comment by Aniket-Engg** [comment]
Is work on it in progress?

**Comment by demurgos** [comment]
There is a replacement ([scrypt-kdf](https://github.com/chrisveness/scrypt-kdf)) based on Node's native scrypt support.
