### ISSUE TITLE
Can't install web3 (scrypt is a dependency) on windows 10

### ISSUE THREAD

**Issue by lukas2005** [barrysteyn/node-scrypt#173]
I get this when trying to install web3 (it fails on the scrypt step)
```
>npm i
npm WARN deprecated fs-promise@2.0.3: Use mz or fs-extra^3.0 with Promise Support
npm WARN deprecated tar.gz@1.0.7: ⚠️  WARNING ⚠️ tar.gz module has been deprecated and your application is vulnerable. Please use tar module instead: https://npmjs.com/tar

> scrypt@6.0.3 preinstall D:\Programy\Deweloping\Projekty\js\Decentracord\node_modules\scrypt
> node node-scrypt-preinstall.js


> scrypt@6.0.3 install D:\Programy\Deweloping\Projekty\js\Decentracord\node_modules\scrypt
> node-gyp rebuild


D:\Programy\Deweloping\Projekty\js\Decentracord\node_modules\scrypt>if not defined npm_config_node_gyp (node "C:\Users\Lukasz\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Lukasz\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Traceback (most recent call last):
  File "C:\Users\Lukasz\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 13, in <module>
    import gyp
  File "C:\Users\Lukasz\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 8, in <module>
    import gyp.input
  File "C:\Users\Lukasz\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\input.py", line 5, in <module>
    from compiler.ast import Const
ImportError: No module named ast
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Users\Lukasz\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 10.0.17083
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Lukasz\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\Programy\Deweloping\Projekty\js\Decentracord\node_modules\scrypt
gyp ERR! node -v v8.6.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lukasz\AppData\Roaming\npm-cache\_logs\2018-04-30T22_12_02_862Z-debug.log
```
Anyone knows a solution?

**Comment by sivahanuman** [comment]
hi lucas facing same issue, have you find the solution ?

**Comment by lukas2005** [comment]
I just reinstalled my whole pc (not because of this) and after installing node I just ran `npm i -g --production windows-build-tools` in cmd

**Comment by sivahanuman** [comment]
You had format your pc because this  web3 Installation issue.

**Comment by lukas2005** [comment]
`I just reinstalled my whole pc (not because of this)`
