### ISSUE TITLE
Error Installing scrypt in windows 10 

### ISSUE THREAD

**Issue by sivahanuman** [barrysteyn/node-scrypt#176]
Hi,

I can't install scrypt in windows 10 , I am getting following error.

`$ npm install scrypt

> scrypt@6.0.3 preinstall D:\solidity\inbox\node_modules\scrypt
> node node-scrypt-preinstall.js

> scrypt@6.0.3 install D:\solidity\inbox\node_modules\scrypt
> node-gyp rebuild

D:\solidity\inbox\node_modules\scrypt>if not defined npm_config_node_gyp (node "C:\Users\siva.subramanian\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\siva.subramanian\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Warning: Missing input files:
D:\solidity\inbox\node_modules\scrypt\build\..\scrypt\win\include\config.h
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
D:\solidity\inbox\node_modules\scrypt\build\copied_files.vcxproj(20,3): error MSB4019: The imported project "D:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
D:\solidity\inbox\node_modules\scrypt\build\scrypt_wrapper.vcxproj(20,3): error MSB4019: The imported project "D:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\siva.subramanian\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:127:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\siva.subramanian\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\solidity\inbox\node_modules\scrypt
gyp ERR! node -v v9.7.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN webpack-cli@2.1.5 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN inbox@1.0.0 No description
npm WARN inbox@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\siva.subramanian\AppData\Roaming\npm-cache\_logs\2018-06-19T02_05_43_201Z-debug.log
`

**Comment by regattatropicals** [comment]
On Windows 10, Scrypt is built using node-gyp, which can be acquired by globally installing Microsoft's Windows Build Tools, so install that first:
`npm install --global --production windows-build-tools`
It takes a while.
Then you should be able to run 
`npm install scrypt`

**Comment by sivahanuman** [comment]
I have tried the command before post here , doesn't work

**Comment by ml1nk** [comment]
My last try with 
`npm install --global --production windows-build-tools`
wasn't successful, too. I installed the build tools directly, then it worked.

Alternative this issue seems to address the same problem
https://github.com/nodejs/node-gyp/issues/671

**Comment by sivahanuman** [comment]
I have tried directly install build tools before post here , doesn't work

**Comment by sivahanuman** [comment]
Hi,
this is the error.
machine configuration 
Windows 10 64 bit, 
Visual studio 2012
Visual Studio 2017
.net Frameworks 3.5 and 4.7,2 ( backward compatibility )

`
$ npm install scrypt

> scrypt@6.0.3 preinstall D:\solidity\inbox\node_modules\scrypt
> node node-scrypt-preinstall.js


> scrypt@6.0.3 install D:\solidity\inbox\node_modules\scrypt
> node-gyp rebuild


D:\solidity\inbox\node_modules\scrypt>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Warning: Missing input files:
D:\solidity\inbox\node_modules\scrypt\build\..\scrypt\win\include\config.h
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
D:\solidity\inbox\node_modules\scrypt\build\copied_files.vcxproj(20,3): error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v110\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
D:\solidity\inbox\node_modules\scrypt\build\scrypt_wrapper.vcxproj(20,3): error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v110\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
gyp ERR! build error
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:127:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\solidity\inbox\node_modules\scrypt
gyp ERR! node -v v9.7.1
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm WARN webpack-cli@2.1.5 requires a peer of webpack@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN inbox@1.0.0 No description
npm WARN inbox@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\siva.subramanian\AppData\Roaming\npm-cache\_logs\2018-06-20T06_10_33_432Z-debug.log

`

**Comment by ml1nk** [comment]
Something is probably wrong with your configuration, as error messages like
"MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v110\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the declaration is correct, and that the file exists on disk." leads to the issue in my previous post and pages like:
[https://www.codesd.com/item/why-does-msbuild-look-in-c-for-microsoft-cpp-default-props-instead-of-c-program-files-x86-msbuild-error-msb4019.html](https://www.codesd.com/item/why-does-msbuild-look-in-c-for-microsoft-cpp-default-props-instead-of-c-program-files-x86-msbuild-error-msb4019.html)

**Comment by sivahanuman** [comment]
Nope doesn't help

**Comment by sivahanuman** [comment]
finally successfully installed

**workaround** 

1. reinstall vc++ build tools for vs2015

2. Manually add the string 
key = VCTargetsPath  
value = C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\v140

**Comment by chrisveness** [comment]
@sivahanuman if you are using Node [v10.5.0 (current)](https://nodejs.org/en/blog/release/v10.5.0/), scrypt has finally been released as part of the [crypto](https://nodejs.org/api/crypto.html#crypto_crypto_scrypt_password_salt_keylen_options_callback) module: I have written a zero-dependency npm module [scrypt-kdf](https://www.npmjs.com/package/scrypt-kdf) which you might find interesting as it has none of the issues of native abstractions, and which I would be glad for you to try out.

It has a slightly simplified API compared with this module (it is promise-based and interfaces with strings rather than buffers), but it operates on the same stored password hashes.

If you try it, let me know your experiences! @chrisveness

**Comment by jaipraveen51** [comment]
@chrisveness 

I tried to install scrypt-kdf but below error

![image](https://user-images.githubusercontent.com/38549767/43367535-271c4fb0-936c-11e8-85b5-ad8b424a9e41.png)

My original intention was to npm install a github downloaded package related to ethereum/solidity

I encountered config.h missing input file error and I tried setting up windows-build-tools command and tried few other options, so far no luck.

Can you please advise? I have already posted a message at scrypt issue page yesterday.

**Comment by ashishrp** [comment]
@sivahanuman what's node -v

**Comment by chrisveness** [comment]
@jaipraveen51 I can't quite make sense of that screenshot, but it looks like errors coming from scrypt, rather than scrypt-kdf - try making sure scrypt is removed from package.json (with scrypt-kd in its place), delete the node_modules directory, and run `npm install` again.

**Comment by sriharikapu** [comment]
This is crazy the node-gyp doesn't work at all. I tried all the ways.
What all I tried: 
1. Python issue - install new python 2.7 and set path - still `node-gpy` it didn't work
2. Install build tools from the VS - still `node-gpy` it didn't work
3. Build build tools from the github - still `node-gpy` it didn't work
4. Rebuild `node-gyp` - still `node-gpy` it didn't work

 
![image](https://user-images.githubusercontent.com/6247133/56018831-c027e280-5d35-11e9-8078-a29434c0ada1.png)


 ` scrypt@6.0.3 install: `node-gyp rebuild` `  Scrypt cannot be installed. 

#RIP

**Comment by chrisveness** [comment]
@sriharikapu, this repo is no longer maintained.

If you are using `scrypt.hash`, it is now available natively in the Node.js [crypto](https://nodejs.org/api/crypto.html#crypto_crypto_scrypt_password_salt_keylen_options_callback) module.

If you are using `scrypt.kdf` / `scrypt.verifyKdf`, [scrypt-kdf](https://github.com/chrisveness/scrypt-kdf) is a close-to-direct replacement.

**Comment by sriharikapu** [comment]
@chrisveness I will check and get back to you

**Comment by sriharikapu** [comment]
I was using scrypt.hash

**Comment by sriharikapu** [comment]
same story on my windows :
![tempsnip](https://user-images.githubusercontent.com/6247133/56509047-7ff80980-6558-11e9-9743-5d0f273f92bc.png)

**Comment by chrisveness** [comment]
@sriharikapu use [crypto.scrypt()](https://nodejs.org/api/crypto.html#crypto_crypto_scrypt_password_salt_keylen_options_callback) in Node 10.5.0+, or [scrypt-async](https://www.npmjs.com/package/scrypt-async) for Node < 10.5.0.

**Comment by sriharikapu** [comment]
I am currently using scrypt-async its not working with any node version for me on my windows.

**Comment by japinzonn** [comment]
Hi. 
I had the same problem. What I did was create the entire project by running the cmd command as administrator:
- mkdir my_project
- npm install -y
- npm init -y
- npm install web3 solc @ 0.4.25
- npm install ganache-cli

**Comment by matsushou** [comment]
Downgrading Node.js (npm) works for me.

**Comment by nameEO** [comment]
Windows 10 64 bit
Downgrade Node.js 12.13.0 to Node.js 10.17.0 works.

**Comment by junsp** [comment]
> Windows 10 64 bit
> Downgrade Node.js 12.13.0 to Node.js 10.17.0 works.

Indeed this made my environment to pass the point of installing scrypt, which was somehow required for ethereum-alarm-clock
