### ISSUE TITLE
Error: libstdc++.so.6: version `GLIBCXX_3.4.21' not found

### ISSUE THREAD

**Issue by ztnark** [barrysteyn/node-scrypt#178]
Having this issue on CentOS 7.

Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /src/node_modules/scrypt/build/Release/scrypt.node)
    at Object.Module._extensions..node (module.js:681:18)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/src/node_modules/scrypt/index.js:3:20)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)

**Comment by chrisveness** [comment]
I think Barry may have abandoned this project. If you are using Node.js v10.5.0+, you could try my [scrypt-kdf](https://www.npmjs.com/package/scrypt-kdf), which is a simple pure-JS wrapper around the native OpenSSL implementation of scrypt. If you try it, I would be interested to know whether you have any issues.

**Comment by jablko** [comment]
[Statically linking libstdc++](https://gcc.gnu.org/onlinedocs/gcc/Link-Options.html#index-static-libstdc_002b_002b) solved this for me. In my case:
```
> LDFLAGS=-static-libstdc++ yarn
```

Alternatively you could try dynamically linking against the same version of libstdc++ as is installed on the host system. [docker-lambda](https://github.com/lambci/docker-lambda) might help, if you want to run it on AWS Lambda.
