### ISSUE TITLE
Installing scrypt in windows 7

### ISSUE THREAD

**Issue by gokuflashdev** [barrysteyn/node-scrypt#183]
-windows SDK 7.1, 8.1, 10
- npm v 6.4.1
-node v 8.12.0
-node-gyp v 3.8.0
VisualStudio community 2017 installed 
.NET framework 4.6 installed

I get error like:

>The x64 compilers are not currently installed.
Please go to Add/Remove Programs to update your installation.
.
Setting SDK environment relative to G:\Program Files\Microsoft SDKs\Windows\v7.1
\.
Targeting Windows 7 x64 Debug

>D:\test>npm install scrypt --save

> scrypt@6.0.3 preinstall D:\test\node_modules\scrypt
> node node-scrypt-preinstall.js

> scrypt@6.0.3 install D:\test\node_modules\scrypt
> node-gyp rebuild

>D:\test\node_modules\scrypt>if not defined npm_config_node_gyp (node "G:\Program
 Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\no
de_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "G:\Program Files\nod
ejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Traceback (most recent call last):
  File "G:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\gyp_m
ain.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "G:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib
\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "G:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib
\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "G:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib
\gyp\__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "G:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib
\gyp\__init__.py", line 98, in Load
    generator.CalculateVariables(default_variables, params)
  File "G:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib
\gyp\generator\msvs.py", line 1916, in CalculateVariables
    generator_flags.get('msvs_version', 'auto'))
  File "G:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\gyp\pylib
\gyp\MSVSVersion.py", line 434, in SelectVisualStudioVersion
    versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)

>KeyError: '2017'
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (G:\Program Files\nodejs\node_module
s\npm\node_modules\node-gyp\lib\configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:198:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "G:\\Program Files\\nodejs\\node.exe" "G:\\Program Files\\nodej
s\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\test\node_modules\scrypt
gyp ERR! node -v v8.12.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open 'D:\test\package.json'
npm WARN test No description
npm WARN test No repository field.
npm WARN test No README data
npm WARN test No license field.

>npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional log
ging output above.

>npm ERR! A complete log of this run can be found in:
npm ERR!     G:\Users\goku\AppData\Roaming\npm-cache\_logs\2018-10-04T11_24_27_0
12Z-debug.log

Its something wrong with "The x64 compilers are not currently installed." or something wrong with node-gyp configuration?

**Comment by chrisveness** [comment]
I think Barry may have abandoned this project. If you are using Node.js v10.5.0+, you could try my [scrypt-kdf](https://www.npmjs.com/package/scrypt-kdf), which is a simple pure-JS wrapper around the native OpenSSL implementation of scrypt. I've not tried it on Windows – if you try it, I would be interested to know whether you have any issues.
