### ISSUE TITLE
Build error in middle of npm install, please kindly help!

### ISSUE THREAD

**Issue by WillZhuang** [barrysteyn/node-scrypt#195]
Build error in middle of npm install, please kindly help!

### Environment:
ubuntu version : 18.04
node version: v10.15.3 （v11.15.0 also the same error）
npm version: 6.4.1
node-gyp version: v4.0.0
gcc g++ version: gcc (Ubuntu 8-20180414-1ubuntu2) 8.0.1

### step of error:
cd node-scrypt
npm install

### error log:
```shell
➜  node-scrypt git:(master) ✗ npm install

> scrypt@6.0.3 preinstall /home/user/node-scrypt
> node node-scrypt-preinstall.js


> scrypt@6.0.3 install /home/user/node-scrypt
> node-gyp rebuild

make: Entering directory '/home/user/node-scrypt/build'
  SOLINK_MODULE(target) Release/obj.target/copied_files.node
  COPY Release/copied_files.node
  CC(target) Release/obj.target/scrypt_wrapper/src/util/memlimit.o
make: cc: Command not found
scrypt_wrapper.target.mk:116: recipe for target 'Release/obj.target/scrypt_wrapper/src/util/memlimit.o' failed
make: *** [Release/obj.target/scrypt_wrapper/src/util/memlimit.o] Error 127
make: Leaving directory '/home/user/node-scrypt/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/user/.nvm/versions/node/v11.15.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:193:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:255:12)
gyp ERR! System Linux 4.15.0-50-generic
gyp ERR! command "/home/user/.nvm/versions/node/v11.15.0/bin/node" "/home/user/.nvm/versions/node/v11.15.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/user/node-scrypt
gyp ERR! node -v v11.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2019-05-24T02_50_36_075Z-debug.log

```

**Comment by WillZhuang** [comment]
I changed to ubuntu 16.04, and gcc version as below:

```
➜  ~ gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

and zos npm install is OK.
