### ISSUE TITLE
Support Node v4.0.0

### ISSUE THREAD

**Issue by thehydroimpulse** [barrysteyn/node-scrypt#85]
I haven't really gone into the changes that break scrypt for the latest node version, but a few errors are triggered.

**Comment by barrysteyn** [comment]
Please can you give more detail? Does it compile? Does it only report errors in the tests?

**Comment by thehydroimpulse** [comment]
I just tried re-installing under v4.0.0 and and it fails to compile. Many errors are related to Nan and overall API breaking changes.

```
-
> scrypt@4.0.7 install /Users/daniel/Projects/stacks/node_modules/scrypt
> node-gyp rebuild

  COPY ../scrypt/scrypt-1.1.6/config.h
  SOLINK_MODULE(target) Release/copied_files.node
  CC(target) Release/obj.target/scrypt_wrapper/src/util/salt.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/keyderivation.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/pickparams.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/hash.o
  LIBTOOL-STATIC Release/scrypt_wrapper.a
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/crypto/sha256.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/crypto/crypto_scrypt-sse.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/scryptenc/scryptenc_cpuperf.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/util/memlimit.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/scryptenc/scryptenc.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/crypto/crypto_aesctr.o
  LIBTOOL-STATIC Release/scrypt_lib.a
  CXX(target) Release/obj.target/scrypt/scrypt_node.o
In file included from ../scrypt_node.cc:28:
../node_modules/nan/nan.h:324:27: error: redefinition of 'NanEnsureHandleOrPersistent'
  NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) {
                          ^
../node_modules/nan/nan.h:319:17: note: previous definition is here
  v8::Handle<T> NanEnsureHandleOrPersistent(const v8::Handle<T> &val) {
                ^
../node_modules/nan/nan.h:344:27: error: redefinition of 'NanEnsureLocal'
  NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Handle<T> &val) {
                          ^
../node_modules/nan/nan.h:334:27: note: previous definition is here
  NAN_INLINE v8::Local<T> NanEnsureLocal(const v8::Local<T> &val) {
                          ^
../node_modules/nan/nan.h:757:13: error: no member named 'smalloc' in namespace 'node'
    , node::smalloc::FreeCallback callback
      ~~~~~~^
../node_modules/nan/nan.h:768:12: error: no matching function for call to 'New'
    return node::Buffer::New(v8::Isolate::GetCurrent(), data, size);
           ^~~~~~~~~~~~~~~~~
/Users/daniel/.node-gyp/4.0.0/include/node/node_buffer.h:31:40: note: candidate function not viable: no known conversion
      from 'uint32_t' (aka 'unsigned int') to 'enum encoding' for 3rd argument
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/daniel/.node-gyp/4.0.0/include/node/node_buffer.h:43:40: note: candidate function not viable: 2nd argument
      ('const char *') would lose const qualifier
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
/Users/daniel/.node-gyp/4.0.0/include/node/node_buffer.h:28:40: note: candidate function not viable: requires 2
      arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate, size_t length);
                                       ^
/Users/daniel/.node-gyp/4.0.0/include/node/node_buffer.h:36:40: note: candidate function not viable: requires 5
      arguments, but 3 were provided
NODE_EXTERN v8::MaybeLocal<v8::Object> New(v8::Isolate* isolate,
                                       ^
In file included from ../scrypt_node.cc:28:
../node_modules/nan/nan.h:772:12: error: no viable conversion from 'v8::MaybeLocal<v8::Object>' to
      'v8::Local<v8::Object>'
    return node::Buffer::New(v8::Isolate::GetCurrent(), size);
           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/daniel/.node-gyp/4.0.0/include/node/v8.h:210:7: note: candidate constructor (the implicit copy constructor) not
      viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'const v8::Local<v8::Object> &' for 1st argument
class Local {
      ^
/Users/daniel/.node-gyp/4.0.0/include/node/v8.h:210:7: note: candidate constructor (the implicit move constructor) not
      viable: no known conversion from 'v8::MaybeLocal<v8::Object>' to 'v8::Local<v8::Object> &&' for 1st argument
class Local {
      ^
/Users/daniel/.node-gyp/4.0.0/include/node/v8.h:214:13: note: candidate template ignored: could not match 'Local' against
      'MaybeLocal'
  V8_INLINE Local(Local<S> that)
            ^
/Users/daniel/.node-gyp/4.0.0/include/node/v8.h:326:13: note: candidate template ignored: could not match 'S *' against
      'v8::MaybeLocal<v8::Object>'
  V8_INLINE Local(S* that)
            ^
In file included from ../scrypt_node.cc:28:
../node_modules/nan/nan.h:779:26: error: no member named 'Use' in namespace 'node::Buffer'
    return node::Buffer::Use(v8::Isolate::GetCurrent(), data, size);
           ~~~~~~~~~~~~~~^
In file included from ../scrypt_node.cc:27:
In file included from /Users/daniel/.node-gyp/4.0.0/include/node/node.h:42:
/Users/daniel/.node-gyp/4.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Primitive *volatile' from incompatible
      type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/daniel/.node-gyp/4.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:501:12: note: in instantiation of function template specialization
      'v8::Local<v8::Primitive>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::Undefined(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
                             ^
In file included from ../scrypt_node.cc:27:
In file included from /Users/daniel/.node-gyp/4.0.0/include/node/node.h:42:
/Users/daniel/.node-gyp/4.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Boolean *volatile' from incompatible type
      'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/daniel/.node-gyp/4.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:511:12: note: in instantiation of function template specialization
      'v8::Local<v8::Boolean>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(v8::True(v8::Isolate::GetCurrent())));
           ^
../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
                             ^
In file included from ../scrypt_node.cc:27:
In file included from /Users/daniel/.node-gyp/4.0.0/include/node/node.h:42:
/Users/daniel/.node-gyp/4.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Function *volatile' from incompatible
      type 'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/daniel/.node-gyp/4.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1645:12: note: in instantiation of function template specialization
      'v8::Local<v8::Function>::Local<v8::Value>' requested here
    return NanEscapeScope(NanNew(handle)->Get(kCallbackIndex)
           ^
../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
                             ^
In file included from ../scrypt_node.cc:27:
In file included from /Users/daniel/.node-gyp/4.0.0/include/node/node.h:42:
/Users/daniel/.node-gyp/4.0.0/include/node/v8.h:221:5: error: assigning to 'v8::Object *volatile' from incompatible type
      'v8::Value *'
    TYPE_CHECK(T, S);
    ^~~~~~~~~~~~~~~~
/Users/daniel/.node-gyp/4.0.0/include/node/v8.h:180:37: note: expanded from macro 'TYPE_CHECK'
    *(static_cast<T* volatile*>(0)) = static_cast<S*>(0);      \
                                    ^ ~~~~~~~~~~~~~~~~~~
../node_modules/nan/nan.h:1776:12: note: in instantiation of function template specialization
      'v8::Local<v8::Object>::Local<v8::Value>' requested here
    return NanEscapeScope(
           ^
../node_modules/nan/nan.h:483:30: note: expanded from macro 'NanEscapeScope'
# define NanEscapeScope(val) scope.Escape(Nan::imp::NanEnsureLocal(val))
                             ^
10 errors generated.
make: *** [Release/obj.target/scrypt/scrypt_node.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/daniel/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "/Users/daniel/.nvm/versions/node/v4.0.0/bin/node" "/Users/daniel/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/daniel/Projects/stacks/node_modules/scrypt
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok 
npm ERR! Darwin 14.1.0
npm ERR! argv "/Users/daniel/.nvm/versions/node/v4.0.0/bin/node" "/Users/daniel/.nvm/versions/node/v4.0.0/bin/npm" "install" "scrypt"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE

npm ERR! scrypt@4.0.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt@4.0.7 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the scrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls scrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/daniel/Projects/stacks/npm-debug.log
```

**Comment by barrysteyn** [comment]
Okay, I will look into this. It could be the Nan has not caught up to Node V4.0 yet, in which case, there is nothing we can do but wait. Regarding the breaking API changes, well, that is why we are on a new version :)

**Comment by barrysteyn** [comment]
Oh, wait a minute. Can you please try version 5?

**Comment by thehydroimpulse** [comment]
@barrysteyn Sent your a PR based on version 5 to fix the issues.

**Comment by Bx1** [comment]
the same on 5.0

**Comment by barrysteyn** [comment]
Ummm - I don't get this. Look on line 35, it states using Nan::Set

How can the compiler get confused by ambiguity? Can you output the compiler  message for me please?

**Comment by thehydroimpulse** [comment]
@barrysteyn 

Here's the compiler output:

```
  COPY ../scrypt/scrypt-1.1.6/config.h
  SOLINK_MODULE(target) Release/copied_files.node
  CC(target) Release/obj.target/scrypt_wrapper/src/util/salt.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/keyderivation.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/pickparams.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/hash.o
  LIBTOOL-STATIC Release/scrypt_wrapper.a
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/crypto/sha256.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/crypto/crypto_scrypt-sse.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/scryptenc/scryptenc_cpuperf.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/util/memlimit.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/scryptenc/scryptenc.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/crypto/crypto_aesctr.o
  LIBTOOL-STATIC Release/scrypt_lib.a
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_common.o
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_async.o
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_sync.o
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_kdf_async.o
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_kdf_sync.o
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_kdf-verify_sync.o
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_kdf-verify_async.o
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_hash_sync.o
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_hash_async.o
  CXX(target) Release/obj.target/scrypt/scrypt_node.o
../scrypt_node.cc:54:2: error: reference to 'Set' is ambiguous
        Set(target, Nan::New<String>("paramsSync").ToLocalChecked(),
        ^
../scrypt_node.cc:35:12: note: candidate found by name lookup is 'Set'
using Nan::Set;
           ^
../scrypt_node.cc:35:12: note: candidate found by name lookup is 'Set'
/Users/daniel/.node-gyp/4.0.0/include/node/v8.h:3021:17: note: candidate found by name lookup is 'v8::Set'
class V8_EXPORT Set : public Object {
                ^
../scrypt_node.cc:57:2: error: reference to 'Set' is ambiguous
        Set(target, Nan::New<String>("params").ToLocalChecked(),
        ^
../scrypt_node.cc:35:12: note: candidate found by name lookup is 'Set'
using Nan::Set;
           ^
../scrypt_node.cc:35:12: note: candidate found by name lookup is 'Set'
/Users/daniel/.node-gyp/4.0.0/include/node/v8.h:3021:17: note: candidate found by name lookup is 'v8::Set'
class V8_EXPORT Set : public Object {
                ^
../scrypt_node.cc:60:2: error: reference to 'Set' is ambiguous
        Set(target, Nan::New<String>("kdfSync").ToLocalChecked(),
        ^
../scrypt_node.cc:35:12: note: candidate found by name lookup is 'Set'
using Nan::Set;
           ^
../scrypt_node.cc:35:12: note: candidate found by name lookup is 'Set'
/Users/daniel/.node-gyp/4.0.0/include/node/v8.h:3021:17: note: candidate found by name lookup is 'v8::Set'
class V8_EXPORT Set : public Object {
                ^
../scrypt_node.cc:63:2: error: reference to 'Set' is ambiguous
        Set(target, Nan::New<String>("kdf").ToLocalChecked(),
        ^
../scrypt_node.cc:35:12: note: candidate found by name lookup is 'Set'
using Nan::Set;
           ^
../scrypt_node.cc:35:12: note: candidate found by name lookup is 'Set'
/Users/daniel/.node-gyp/4.0.0/include/node/v8.h:3021:17: note: candidate found by name lookup is 'v8::Set'
class V8_EXPORT Set : public Object {
                ^
../scrypt_node.cc:66:2: error: reference to 'Set' is ambiguous
        Set(target, Nan::New<String>("verifySync").ToLocalChecked(),
        ^
../scrypt_node.cc:35:12: note: candidate found by name lookup is 'Set'
using Nan::Set;
           ^
../scrypt_node.cc:35:12: note: candidate found by name lookup is 'Set'
/Users/daniel/.node-gyp/4.0.0/include/node/v8.h:3021:17: note: candidate found by name lookup is 'v8::Set'
class V8_EXPORT Set : public Object {
                ^
../scrypt_node.cc:69:2: error: reference to 'Set' is ambiguous
        Set(target, Nan::New<String>("verify").ToLocalChecked(),
        ^
../scrypt_node.cc:35:12: note: candidate found by name lookup is 'Set'
using Nan::Set;
           ^
../scrypt_node.cc:35:12: note: candidate found by name lookup is 'Set'
/Users/daniel/.node-gyp/4.0.0/include/node/v8.h:3021:17: note: candidate found by name lookup is 'v8::Set'
class V8_EXPORT Set : public Object {
                ^
../scrypt_node.cc:72:2: error: reference to 'Set' is ambiguous
        Set(target, Nan::New<String>("hashSync").ToLocalChecked(),
        ^
../scrypt_node.cc:35:12: note: candidate found by name lookup is 'Set'
using Nan::Set;
           ^
../scrypt_node.cc:35:12: note: candidate found by name lookup is 'Set'
/Users/daniel/.node-gyp/4.0.0/include/node/v8.h:3021:17: note: candidate found by name lookup is 'v8::Set'
class V8_EXPORT Set : public Object {
                ^
../scrypt_node.cc:75:2: error: reference to 'Set' is ambiguous
        Set(target, Nan::New<String>("hash").ToLocalChecked(),
        ^
../scrypt_node.cc:35:12: note: candidate found by name lookup is 'Set'
using Nan::Set;
           ^
../scrypt_node.cc:35:12: note: candidate found by name lookup is 'Set'
/Users/daniel/.node-gyp/4.0.0/include/node/v8.h:3021:17: note: candidate found by name lookup is 'v8::Set'
class V8_EXPORT Set : public Object {
                ^
8 errors generated.
make: *** [Release/obj.target/scrypt/scrypt_node.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/daniel/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "/Users/daniel/.nvm/versions/node/v4.0.0/bin/node" "/Users/daniel/.nvm/versions/node/v4.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/daniel/cloned/node-scrypt
gyp ERR! node -v v4.0.0
gyp ERR! node-gyp -v v3.0.1
gyp ERR! not ok 

npm ERR! Darwin 14.1.0
npm ERR! argv "/Users/daniel/.nvm/versions/node/v4.0.0/bin/node" "/Users/daniel/.nvm/versions/node/v4.0.0/bin/npm" "install"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! scrypt@5.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt@5.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the scrypt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls scrypt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/daniel/cloned/node-scrypt/npm-debug.log
```

It's ambiguous because you also have

```cpp
using namespace v8;
```

which is also exporting a `Set` class.

**Comment by barrysteyn** [comment]
Okay, this makes sense, it must be new in Node version 4. There is a way out of this ambiguity (as you have done) which is to explicitly refer to the namespace.
