### ISSUE TITLE
Build Error With Node 4.1.0

### ISSUE THREAD

**Issue by larron** [barrysteyn/node-scrypt#90]
Hey Barry,
I decided to give 4.1.0 a try and ran into some issues with what seems to be scrypt.
I was able to install node-gyp globally.
Here's what happens when I try to install scrypt into a local project:

```
> node-gyp rebuild

  COPY ../scrypt/scrypt-1.1.6/config.h
  SOLINK_MODULE(target) Release/copied_files.node
  CC(target) Release/obj.target/scrypt_wrapper/src/util/salt.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/keyderivation.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/pickparams.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/hash.o
  LIBTOOL-STATIC Release/scrypt_wrapper.a
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/crypto/sha256.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/crypto/crypto_scrypt-sse.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/scryptenc/scryptenc_cpuperf.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/util/memlimit.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/scryptenc/scryptenc.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/crypto/crypto_aesctr.o
  LIBTOOL-STATIC Release/scrypt_lib.a
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_common.o
../src/node-boilerplate/scrypt_common.cc:25:10: fatal error: 'nan.h' file not found
#include <nan.h>

1 error generated.
make: *** [Release/obj.target/scrypt/src/node-boilerplate/scrypt_common.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
```

On the flip side, I was able to clone and build scrypt manually and get it to work!
Thanks

**Comment by barrysteyn** [comment]
It works for me:

```
gyp info it worked if it ends with ok
gyp info using node-gyp@1.0.2
gyp info using node@4.1.0 | darwin | x64
(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
gyp info spawn python
gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Barry/Personal/Git/GitHub/node-scrypt/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/Barry/.node-gyp/4.1.0/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/Barry/.node-gyp/4.1.0',
gyp info spawn args   '-Dmodule_root_dir=/Users/Barry/Personal/Git/GitHub/node-scrypt',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
  COPY ../scrypt/scrypt-1.1.6/config.h
  SOLINK_MODULE(target) Release/copied_files.node
  SOLINK_MODULE(target) Release/copied_files.node: Finished
  CC(target) Release/obj.target/scrypt_wrapper/src/util/salt.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/keyderivation.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/pickparams.o
  CC(target) Release/obj.target/scrypt_wrapper/src/scryptwrapper/hash.o
  LIBTOOL-STATIC Release/scrypt_wrapper.a
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/crypto/sha256.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/crypto/crypto_scrypt-sse.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/scryptenc/scryptenc_cpuperf.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/util/memlimit.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/scryptenc/scryptenc.o
  CC(target) Release/obj.target/scrypt_lib/scrypt/scrypt-1.1.6/lib/crypto/crypto_aesctr.o
  LIBTOOL-STATIC Release/scrypt_lib.a
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_common.o
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_async.o
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_sync.o
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_kdf_async.o
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_kdf_sync.o
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_kdf-verify_sync.o
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_kdf-verify_async.o
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_hash_sync.o
  CXX(target) Release/obj.target/scrypt/src/node-boilerplate/scrypt_hash_async.o
  CXX(target) Release/obj.target/scrypt/scrypt_node.o
  SOLINK_MODULE(target) Release/scrypt.node
  SOLINK_MODULE(target) Release/scrypt.node: Finished
gyp info ok
```

I don't know what you have done incorrectly, but I suggest you remove your `node_modules` folder, and install it with npm (as in `npm install scrypt`)
